import pyvisa
import time
rm = pyvisa.ResourceManager()
potential_source = rm.open_resource('GPIB::10::INSTR')

potential_source.write('OUTP ON')
time.sleep(0.5)
potential_source.write('VOLT:PROT:STAT OFF')
time.sleep(0.5)
potential_source.write('CAL:SEC:STAT OFF, "003641"')
time.sleep(0.5)
potential_source.write('CAL:VOLT:LEV MIN')
time.sleep(0.5)
potential_source.write('CAL:VOLT:DATA 0.549')
time.sleep(0.5)
potential_source.write('CAL:VOLT:LEV MID')
time.sleep(0.5)
potential_source.write('CAL:VOLT:DATA 11.058')
time.sleep(0.5)
potential_source.write('CAL:VOLT:LEV MAX')
time.sleep(0.5)
potential_source.write('CAL:VOLT:DATA 21.566')
time.sleep(0.5)
potential_source.write('CAL:VOLT:PROT')
time.sleep(0.5)
potential_source.write('CAL:STR "nova calibracao - 03 2023, Roberto"')
